### ISSUE TITLE
website content missing

### ISSUE THREAD

**Issue by andreashandel** [epid8060fall2019/PaigeDuffin-DataAnalysis#1]
your variable selection exercise is not on the website. you might need to update all website related parts for things to show properly.

**Comment by paigeduffin** [comment]
I'm sorry, I just saw this. It should be working right now.

Do you know how I can turn on notifications so I see all issues opened on any of my EPID 8060 repositories?

**Comment by andreashandel** [comment]
works now. see eLC announcement for changing notification alerts.
